routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('account', 'AccountController', ['only' => [
    'index', 'create', 'store','show']])->names('account');

Route::resource('payment', 'PaymentController', ['except' => [
    'index','show']])->names('payment');

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use App\Model\Account;
use App\Model\Payment;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view('accounts.index', ['accounts' => Account::with('payments')->get()]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        return view('accounts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return void
     */
    public function store(Request $request)
    {
        $item = Account::create();
        if ($item) {
            return redirect()->route('account.index')->with(['success' => 'Saved']);
        }
        return back()->withErrors(['msg' => 'Errors'])
            ->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param Account $account
     * @return Response
     */
    public function show(Account $account)
    {
        return view('accounts.show', compact('account'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Model\Account;
use App\Model\Payment;
use App\Service\BalanceAccountService;
use App\Service\PaymentService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class PaymentController extends Controller
{
    /**
     * @var CreatePaymentService
     */
    private $balanceAccountService;

    /**
     * PaymentController constructor.
     * @param PaymentService $paymentService
     * @param BalanceAccountService $balanceAccountService
     */
    public function __construct(BalanceAccountService $balanceAccountService)
    {
        $this->balanceAccountService = $balanceAccountService;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('payment.create_edit', ['payment' => new Payment(), 'account' => Account::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $item = Payment::create($request->input());
        if ($item) {
            $this->balanceAccountService->addOrSubSum($item, balanceAccountService::ADD);
            return redirect()->route('account.index')->with(['success' => 'Saved']);
        }
        return back()->withErrors(['msg' => 'Errors'])
            ->withInput();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Payment $payment
     * @return Response
     */
    public function edit(Payment $payment)
    {
        return view('payment.create_edit', ['payment' => $payment, 'account' => Account::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Payment $payment
     * @return Response
     */
    public function update(Request $request, Payment $payment)
    {
        $item = clone $payment;
        if ($payment->update($request->input())) {
            $this->balanceAccountService->newBalance($item, $payment);
            return back()->with(['success' => "Saved"]);
        }
        return back()->withErrors(['msg' => "Error"])
            ->withInput();
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param Payment $payment
     * @return Response
     * @throws \Exception
     */
    public function destroy(Payment $payment)
    {
        if ($payment->delete()) {
            $this->balanceAccountService->addOrSubSum($payment, balanceAccountService::SUB);
            return back()->with(['success' => "Deleted"]);
        }
    }
}

resources/views/accounts/create.blade.php
@extends('layouts.app')

@section('content')
    @include('includes.result_messages')
    <h1 class="my-4">Create account
    </h1>
    <form method="POST" action="{{ route('account.store')}}">
        @csrf
        <button type="submit" class="btn btn-success">Сonfirm creation</button>
    </form>
@endsection

resources/views/accounts/index.blade.php
@extends('layouts.app')
@section('content')
    @include('includes.result_messages')
    @foreach($accounts as $item )
        <div class="card mb-4">
            <div class="card-body">
                <a href="{{ route('account.show', $item->id)}}">
                    <h2 class="card-title">Account {{$item->id}}</h2>
                </a>
                <p class="card-text">Balance: {{$item->balance}}</p>
            </div>
            <div class="card-footer text-muted">
                Created: {{$item->created_at}}
            </div>
        </div>
    @endforeach
@endsection

resources/views/accounts/show.blade.php
@extends('layouts.app')
@section('content')
    @include('includes.result_messages')
    <a class="btn btn-secondary" href="{{ route('payment.create')}}" role="button">Add
        payment</a>
    <div class="card mb-4">
        <div class="card-body">
            <h2 class="card-title">Account {{$account->id}}</h2>
            <p class="card-text">Balance: {{$account->balance}}</p>
        </div>
        <div class="card-footer text-muted">
            @foreach($account->payments as $item)
                Payment: {{$item->id}} -> sum = {{$item->sum}}
                <br>
                <a class="btn btn-secondary" href="{{ route('payment.edit',$item->id) }}"
                   role="button">Edit</a>
                <form method="POST" action="{{route('payment.destroy',$item->id) }}">
                    @method('DELETE')
                    @csrf
                    <button class="btn btn-secondary"
                            type="submit">Delete
                    </button>
                </form>
                <br>
            @endforeach
        </div>
    </div>
@endsection

resources/views/includes/result_messages.blade.php
@if($errors->any())
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="alert alert-danger" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                @foreach($errors->all() as $errorTxt)
                    <li>{{ $errorTxt}}</li>
                @endforeach
            </div>
        </div>
    </div>
@endif

@if(session('success'))
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                {{ session()->get('success') }}
            </div>
        </div>
    </div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog</title>


    <link href="{{asset('css/app.css')}}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{{route('account.index')}}">Main</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ route('account.create') }}" }>Create account
                        <span class="sr-only">(current)</span>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <main>
                @yield('content')
            </main>
        </div>
    </div>
</div>
<script src="{{asset('js/app.js')}}"></script>

</body>

</html>

resources/views/payment/create_edit.blade.php
@extends('layouts.app')

@section('content')
    @include('includes.result_messages')
    @if($payment->exists)
        <h1 class="my-4">Edit payment</h1>
        <form method="POST" action="{{ route('payment.update', $payment->id )}}">
            @method('PATCH')
            @else
                <h1 class="my-4">Create payment
                </h1>
                <form method="POST" action="{{ route('payment.store')}}">
                    @endif
                    @csrf
                    <div class="form-group">
                        <label for="name">Sum</label>
                        <input name="sum"
                               id="sum"
                               type="text"
                               class="form-control"
                               value="{{ old('sum', $payment->sum) }}">
                    </div>
                    <div class="form-group">
                        <label for="account_id">Account</label>
                        <select name="account_id"
                                id="account_id"
                                class="form-control"
                                placeholder="Select account"
                                required>
                            @foreach($account as $accountOption)
                                <option value="{{ $accountOption->id }}"
                                        @if($accountOption->id == $payment->account_id) selected @endif>
                                    Account: {{$accountOption->id}}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success" dusk="save">Save</button>
                </form>
@endsection